deployment:
  name: webapp-deployment
  replicaCount: 3

image: anusri1908/helm:40
  repository: 
  pullPolicy: Always
  containerName: useraccount
  imagePullSecrets: dockerhub
  containerPort: 3080
  
service:
  type: ClusterIP
  clusterIPPort: 80

