deployment:
  name: webapp-deployment
  replicaCount: 3

image: 
  repository: anusri1908/helm:47
  pullPolicy: Always
  containerName: useraccount
  imagePullSecrets: dockerhub
  containerPort: 3080
  
service:
  type: ClusterIP
  clusterIPPort: 80

